services:
  - type: web
    name: playerpro
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: YOUTUBE_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 8080
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: playerpro-disk
      mountPath: /app/downloads
      sizeGB: 1